### ISSUE TITLE
No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version')

### ISSUE THREAD

**Issue by Terfender** [appodeal/react-native-appodeal#3]
Hi,
I am getting this error when building my RN project as well as the example project in this repo.
I made sure I have google-play-service installed via Android Studio SDK Manager. 

Added to my app build.gradle
```
    compile "com.google.android.gms:play-services-ads:9.8.0"
    compile "com.google.android.gms:play-services-location:9.8.0"
```

I also tried to update using the latest google-play-service version.

Adding `apply plugin: 'com.google.gms.google-services'` in build.gradle didn't help

**Comment by kurtsergey** [comment]
the same issue

**Comment by NathHorrigan** [comment]
same issue

**Comment by sneerin** [comment]
I spent some time to fix it: 
https://github.com/sneerin/react-native-appodeal/
as a temporary solution
You have to add     compile 'com.android.support:recyclerview-v7:23.1.1' to your build.gradle, I did it because I have multidex in my app.

**Comment by NathHorrigan** [comment]
@sneerin  Fucking Awesome dude, How come you haven't created PR??

**Comment by sneerin** [comment]
because i'm not sure if it will be working for you, you can check,  it's just two file changes there. So as a temporary solution you can include it to your product in package.json "react-native-appodeal": "https://github.com/sneerin/react-native-appodeal.git", and if an owner of this repo will fix it just replace it with the original package.

**Comment by sneerin** [comment]
Please also be aware, that maintainers of the code didn't not deprecate several types of ads, so that once you try non-skipable video it's just failed to show without any warning or so.

**Comment by NathHorrigan** [comment]
@sneerin I'm running out of memory building after linking your lib

**Comment by sneerin** [comment]
do you have multi-dex app?

**Comment by sneerin** [comment]
also, is this your first time you integrate this lib, I remember my app become multi-dex, and run out of memory this is ok, since this lib includes lot's of third party shit.

**Comment by NathHorrigan** [comment]
After a restart everything worked - Thanks!!

**Comment by jsoutherner** [comment]
Still have a problem.
Found interesting thing on website - https://www.appodeal.com/sdk/documentation?framework=12&full=1&platform=1

Seem like its not new problem. But what is the official solution for react-native?

**Comment by Tamplier** [comment]
Hey guys! Sorry for the delay. The issue was fixed in the last update. You can download the new version or just add the following dependencies to plugin's buld.gradle ([your_project]/node_modules/react-native-appodeal/android/build.gradle):
```
compile "com.google.android.gms:play-services-ads:9.8.0"
compile "com.google.android.gms:play-services-location:9.8.0"
```
You don't need these dependencies in your main build.gradle anymore.
If it won't help, feel free to reopen the issue.

**Comment by Evaske** [comment]
I'm still getting this issue. 

Gradle 3.0.1. I have the above in my build.gradle and get the following error:

`/Users/user/Development/app/node_modules/react-native-appodeal/android/build/intermediates/manifests/aapt/release/AndroidManifest.xml:49: error: resource integer/google_p
lay_services_version (aka com.reactlibrary:integer/google_play_services_version) not found.`

**Comment by Bharatchavan20** [comment]
Facing same issue.

**Comment by shanematte** [comment]
> Hey guys! Sorry for the delay. The issue was fixed in the last update. You can download the new version or just add the following dependencies to plugin's buld.gradle ([your_project]/node_modules/react-native-appodeal/android/build.gradle):
> 
> ```
> compile "com.google.android.gms:play-services-ads:9.8.0"
> compile "com.google.android.gms:play-services-location:9.8.0"
> ```
> You don't need these dependencies in your main build.gradle anymore.
> If it won't help, feel free to reopen the issue.

Thanks. I spent 5 hours fixing this error. But when you install a new package, no dependencies were added. Had to manually

**Comment by king804** [comment]
> can

any update?
